#if desired can make "ind_file" for structure. This is an ordred list of sample names in column 1 with state names (populations) in column 2.
# However, to start we are not using this info and just using the most basic format of a matrix of genotypes
make_ind_file_structure.r
#format conversion
structure_format.r

#upload the structure formatted snp file to server in their respective dirs, Nf_SPANDx_all_seqs_structure_th and Nd_SPANDx_all_seqs_structure_th
# The ind_files are in the repo

module purge
module load linuxbrew/colsa
cd Nf_SPANDx_all_seqs_structure_th
cp ~/repo/neonectria_SNP/pop_gen/structure/Nf_ind_file.structure ./ind_file.structure


### Running structure_threader
First generate the params files
```
cd
mkdir Nf_SPANDx_all_seqs_structure_th
module purge
module load anaconda/colsa
export PATH=~/.local/bin:$PATH

cd Nf_SPANDx_all_seqs_structure_th
structure_threader params -o ~/Nf_SPANDx_all_seqs_structure_th/

```
Download the params file to edit and retain a local copy if desired. The default parameters generated by structure_threader in `extraparams` are satisfactory.
#### Edits to `mainparams`
- set
- PLOIDY to 1
- NUMINDS 105 #after filtering out seuqncing reps and high missing data
- NUMLOCI 39849 #SNPs remaining after pgspider
- MISSING -9
- LABEL 1
- POPDATA 0
- MAXPOPS 15 #although this is set by -K on the command line

Run structure_threader (started at 5/27 2p)
```
cd ~/Nf_SPANDx_all_seqs_structure_th/
sbatch ~/repo/neonectria_SNP/pop_gen/structure/Nf_structure_threader.slurm
```
